# Generated by Django 2.1.7 on 2019-02-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cabprosessing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestid', models.PositiveIntegerField(verbose_name=32482)),
                ('servicetype', models.CharField(max_length=250)),
                ('source', models.CharField(max_length=250)),
                ('destnation', models.CharField(max_length=250)),
                ('Date', models.DateField()),
                ('Pickuptime', models.TimeField()),
                ('issuedto', models.CharField(max_length=250)),
                ('Empid', models.PositiveIntegerField()),
                ('Drivername', models.CharField(max_length=250)),
                ('ststus', models.CharField(max_length=250)),
                ('fare', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='consumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_type', models.CharField(max_length=250)),
                ('Empid', models.PositiveIntegerField(max_length=250)),
                ('password', models.CharField(max_length=20)),
                ('Fname', models.CharField(max_length=250)),
                ('Mname', models.CharField(max_length=250)),
                ('Lname', models.CharField(max_length=250)),
                ('Email', models.EmailField(max_length=250)),
                ('Phone', models.PositiveIntegerField(max_length=10)),
                ('Address', models.TextField()),
                ('Mgname', models.CharField(max_length=250)),
                ('Mg_email', models.CharField(max_length=250)),
                ('Location', models.TextField()),
            ],
        ),
    ]
